name: opml
description: A Dart package for parsing and building Outline Processor Markup Language (OPML) documents.
version: 0.3.0
homepage: https://github.com/daniel-keogh/opml

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  xml: ^6.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.1
